[server]
headless = true
enableCORS = false
enableXsrfProtection = true
address = "0.0.0.0"
port = 8501

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false

# Tambahkan ini untuk HTTPS
[server.ssl]
certFile = "/etc/ssl/certs/cert.pem"
keyFile = "/etc/ssl/private/key.pem"
