[server]
headless = true
enableCORS = true  # Harus true karena enableXsrfProtection=true
enableXsrfProtection = true
address = "0.0.0.0"
port = 8501

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false

# HAPUS bagian ssl, tidak support
